import os
import SalesData # file generated by ReadSalesCsv.py
import datetime

INPUT_FILENAME = r'.\Movie List.txt'
OUTPUT_FILENAME = r'.\MoveList.html'
OUTPUT_FILENAME_UNMATCHED = r'.\MovieList_Unmatched.txt'
FIRST_DATA_LINE = 4
SALESDATA_FILENAME = r'.\SalesData.py'
OUTPUT_COLUMN_COUNT = 1

def MakeEntry(sales, line, matchedKeys):
	
	prefix = ''
	searchkey = line[:len(line)-5].strip() # take year off of the end of the movie name to use as the key
	
	if searchkey in sales.keys():
		matchedKeys.append(searchkey)
		match = sales[searchkey]
		prefix = f'{match[0]}-{match[1]}'
	
	return f'\t<td class="count">{prefix}</td><td class="description">{line}</td>'

# read movie list
with open(INPUT_FILENAME, 'r') as infile:
	lines = infile.readlines()

lineCounter = 0
matchedKeys = []

# html header
output = '<html>\n'
output += '''
<style type="text/css">
\t.count {font-family:monospace;font-size:8px; width:30px; border:0px;}
\t.description {font-size:10px; border:0px; padding-right:10px;}
\tTABLE {border:none;border-collapse:collapse;}
\tTR {border:none;}
</style>\n
'''

output += '<table cellpadding="0" cellspacing="0">\n'

for line in lines:
	lineCounter += 1
	line = line.strip()

	if lineCounter <= FIRST_DATA_LINE:
		output += (f'\t<tr><td colspan="2" class="description">{line}</td></tr>\n')
		continue

	if lineCounter == FIRST_DATA_LINE + 1:
		output += '\t<tr><td colspan="2">&nbsp;</td></tr>\n'
		output += '</table>\n'
		output += '<table cellpadding="0" cellspacing="0">\n\t<tr>\n'
		continue

	output += f'\t{MakeEntry(SalesData.sales, line, matchedKeys)}\n'
	
	if (lineCounter + FIRST_DATA_LINE) % OUTPUT_COLUMN_COUNT == 0:
		output += '\t</tr><tr>\n'

output += '</tr></table></html>'

# write output file
with open(OUTPUT_FILENAME, 'w') as outputFile :
	outputFile.write(output)

# write a file that contains unmatched titles
COL_COUNT = 0
COL_AMOUNT = 1
COL_DATES = 2
with open(OUTPUT_FILENAME_UNMATCHED, 'w') as outputFile:
	outputFile.write(f'# generated {datetime.date.today()}\n\n')
	for k in SalesData.sales.keys():
		if k not in matchedKeys:
			outputFile.write(f'{SalesData.sales[k][COL_DATES]}\t{k}\n')


#print (len(SalesData.sales))	
