# Reads CSV files and puts the data into a dictionary in a py file

import csv
import datetime
import glob
import math
import os
import re
import typing

DATA_FOLDER = r'.\Csv_Sales'
OUTPUT_FILE = r'.\Output\SalesData.py'

COL_DATE = 0
COL_PAYMENTRECEIVED = 1
COL_PAYPALFEE = 2
COL_POSTAGE = 3
COL_OTHERCOSTS = 4
COL_DESCRIPTION = 5
COL_PURCHASEPRICEOFFSET = 6
COL_ITEMPROFIT = 7
COL_MOVIELISTKEY = 8

def ToFloat(inVal):
	returnVal = re.sub('[^0-9\.]', '', inVal)
	try:
		returnVal = float(returnVal)
	except Exception as ex:
		return None

	return returnVal


files = glob.glob(os.path.join(DATA_FOLDER, '*.csv'))
sales: dict = {}
errorList = []

for file in files:
	
	with open(file) as csv_file:
		
		csv_reader = csv.reader(csv_file, delimiter=',')
		line_count = 0
		for row in csv_reader:
			line_count += 1

		
			# data starts on line 4
			if line_count < 4:
				continue

			if len(row[COL_PAYMENTRECEIVED]) > 0:

				description = row[COL_DESCRIPTION]
				amount = ToFloat(row[COL_PAYMENTRECEIVED])
				date = row[COL_DATE]
				movieListKey = row[COL_MOVIELISTKEY] if len(row) > COL_MOVIELISTKEY else ''
				
				# can't convert payment received to float
				if amount is None:
					errorList.append(f'["Bad amount", "{file}", "{row[COL_DATE]}", "{row[COL_PAYMENTRECEIVED]}"]')
					continue

				if ( # we've seen this one before
					description in sales
					or (len(movieListKey) > 0 and movieListKey in sales)
				):
					sales[description][0] += 1
					sales[description][1] += amount
					sales[description][2].append(date)
					sales[description][3] = movieListKey
				elif len(movieListKey) > 0 and movieListKey not in sales: # use movielistkey if it exists
					sales[movieListKey] = [1, amount, [date], movieListKey]
				else: # make a new one
					sales[description] = [1, amount, [date], movieListKey]
				
with open(OUTPUT_FILE, "w") as file:
	file.write(f'# This file generated by ReadSalesCsv.py on {datetime.date.today()}\n')
	file.write('# [Count, Total payment received, Dates, MovieListKey\n')
	file.write('sales={}\n')
	for key in sales.keys():
		dates = ', '.join(sales[key][2])
		file.write(f'sales["{key}"] = ["{sales[key][0]}", "{math.floor(sales[key][1]):03}", "{dates}", "{sales[key][3]}"]\n')

	file.write('\nerrors=[]\n')
	for e in errorList:
		file.write(f'errors.append({e})\n')

